services:
    app:
        build: .
        container_name: bnck-admin-catalogo-app
        volumes:
            - .:/var/www
            - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - app-network

    nginx:
        build: .docker/nginx
        container_name: bnck-admin-catalogo-nginx
        restart: always
        tty: true
        ports:
            - "8088:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    # db:
    #     build: ./.docker/mysql
    #     container_name: bnck-admin-catalogo-db
    #     restart: always
    #     tty: true
    #     ports:
    #         - "33006:3306"
    #     volumes:
    #         - ./.docker/dbdata:/var/lib/mysql
    #         - ./.docker/mysql:/docker-entrypoint-initdb.d
    #     environment:
    #         - MYSQL_DATABASE=code_micro_videos
    #         - MYSQL_ROOT_PASSWORD=root
    #     networks:
    #         - app-network

    # redis:
    #     image: redis:alpine
    #     container_name: bnck-admin-catalogo-redis
    #     networks:
    #         - app-network

networks:
    app-network:
        driver: bridge